# Some solid inspriation borrowed from https://github.com/mediadepot/docker-flatcar-developer/blob/master/.github/workflows/build.yaml
name: Build
on:
  schedule:
    # Every day at 4am
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  info:
    outputs:
      FLATCAR_VERSION: ${{ steps.curl.outputs.FLATCAR_VERSION }}
    runs-on: ubuntu-latest
    steps:
    - id: curl
      run: curl -L https://stable.release.flatcar-linux.net/amd64-usr/current/version.txt | xargs -n1 echo | tee -a "${GITHUB_OUTPUT}"

  check:
    needs: info
    outputs:
      released: ${{ steps.release.outputs.exists }}
    runs-on: ubuntu-latest
    steps:
    - id: release
      run: |
        FLATCAR_VERSION=${{ needs.info.outputs.FLATCAR_VERSION }};
        release_url="https://github.com/${{github.repository}}/releases/download/${FLATCAR_VERSION}/flatcar-zfs-overlay-${FLATCAR_VERSION}.raw";

        echo "Checking if $release_url exists..."
        if curl --output /dev/null --silent --head --fail $release_url; then
          echo "Already Released"
          echo "exists=true" >> "$GITHUB_OUTPUT";
        fi

  build:
    needs: [ info, check ]
    if: ${{ !needs.check.outputs.released }}
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - run: make FLATCAR_VERSION=${{needs.info.outputs.FLATCAR_VERSION}}
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: docker image push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - uses: gautamkrishnar/keepalive-workflow@v1

#   - uses: cardinalby/git-tag-action@v1.0
#     env:
#       TAG: ${{ needs.info.outputs.FLATCAR_VERSION }}
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   - name: Release
#     if: success()
#     uses: softprops/action-gh-release@v1
#     with:
#       tag_name: ${{ needs.info.outputs.FLATCAR_VERSION }}
#       files: "*.raw"
